package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Проверка авторизации в яндекс почте")
    void generatedTest() {
        step("Открыть \"https://mail.yandex.ru/\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Нажать на кнопку \"войти на почту\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Ввести логин gkjw@ya.ru и нажать \"войти\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Ввести пароль sG:KNw\"!@ и нажать \"войти\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Открылась страница с почтой", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://mail.yandex.ru/'", () ->
            open("https://mail.yandex.ru/"));

        step("Page title should have text 'Авторизация'", () -> {
            String expectedTitle = "Авторизация";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://mail.yandex.ru/'", () ->
            open("https://mail.yandex.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}